export const titles = {
  require: 'Todos los campos marcados con * son obligatorios.!',
  successCreate: 'Partida creada correctamente!.',
  successUpdate: 'Partida actualizada correctamente!.',
  successDelete: 'Partida eliminada correctamente!.',
  titleDeleteModal: 'Seguro que desea eliminar la partida: ',
  titleCreate: 'Crear Partida',
  titleUpdate: 'Editar Partida',
  titleDelete: 'Inactivar Partida',
  labelCreate: 'Partida creada',
  labelUpdate: 'Partida actualizada',
  labelDelete: 'Partida eliminada',
  generalError: 'Ups algo salio mal: ',
  generalAction: 'Acciones',
  menuCreate: 'Agregar Partida',
  tableCell1: 'Nombre',
  tableCell2: 'Email',
  tableCell3: 'Perfil',
  tableCell4: 'Estado',
  tableCellActions: 'Acciones',
  maxRecords: 'Registros máximos',
  noRecordsFound: 'No existen partidas aún!',
  buttonCreate: 'Crear',
  buttonUpdate: 'Actualizar',
  buttonDelete: 'Eliminar',
  buttonCancel: 'Cancelar',
  loading: 'Cargando...'
};

export const inputLabels = {
  search: 'searchField',
  name: 'name',
  labelName: 'Nombre',
  labelDate: 'Fecha',
  email: 'email',
  labelEmail: 'E-mail',
  profile: 'profile',
  labelProfile: 'Perfil',
  state: 'State',
  labelState: 'Estado',
  placeHolderSearch: 'Buscar por Nombre o Correo electrónico'
};
